config/routes.rb
Rails.application.routes.draw do
  #devise_for :users do
  #  get '/users/sign_out' => 'devise/sessions#destroy'
  #end

  #devise_for :users, controllers: {
    #registrations: 'users/registrations'
  #}

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "articles#index"
  

  resources :articles do
    resources :comments
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @count = Article.public_count
    if @count ==1
      @article = "article"
    else
      @article = "articles"
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated."
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "Article was successfully deleted."
    else
      flash[:notice] = "Article was NOT deleted."
    end
    redirect_to root_path, status: :see_other
  end

    private
      def article_params
        params.require(:article).permit(:title, :body, :status, :author, :user_id)
      end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, size: "60x10" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="blog-btn-group-vertical">
    <div>
      <%= form.label :status %><br>
      <%= form.select(:status, Visible::VALID_STATUSES, { :class => "form-select form-select-lg", selected: article.status || "public" }) %>
    </div>

    <div>
      <%= form.label :author %><br>
      <%= form.text_field :author, value: current_user.username, hidden: true %>
      <%= current_user.username %>
    </div>

    <div>
      <%= form.hidden_field :user_id, value: current_user.id %>
    </div>

    <div>
      <%= form.submit(class: "btn btn-primary blog-form-btn") %>
    </div>

    <div>
      <%= link_to "Cancel", articles_path, class: "link-danger" %>
    </div>
  </div>
<% end %>

app/views/articles/_welcome.html.erb
<div>
    <h3>Welcome to Jason Minyard's Developer Blog!</h3>
    <p>
        Hello, fellow developers and enthusiasts! I'm Jason Minyard, a passionate Software Developer with a specialization in Ruby on Rails. I look forward to learning a couple more languages to add to my toolbox as well.  With seven years of experience in the software development realm, five of which have been dedicated to learning the intricacies of Ruby, I'm thrilled to share my knowledge and experiences with you through this blog as I go along.
    </p>
    <p>
        Here, my intentions are that you'll find resources tailored to both seasoned developers looking to refresh their skills and newcomers eager to dive into the world of Ruby on Rails.
    </p>
    <p>
        This blog initially emerged as a personal refresher course on writing Ruby on Rails applications, comprehensive testing methodologies, conducting efficient code reviews on GitHub, and seamlessly deploying applications on Heroku.
    </p>
    <p>
        Whether you're embarking on your first Ruby on Rails project or seeking to enhance your existing skills, this blog serves as a comprehensive guide through every stage of the development process. From laying the groundwork for your application to conducting thorough testing, collaborating effectively through code reviews, and finally deploying your masterpiece for the world to see, I'm committed to providing you with practical insights and actionable tips every step of the way.
    </p>
    <p>
        Join me on this exciting journey as we explore the fascinating realm of Ruby on Rails development together. Let's empower ourselves with knowledge, elevate our coding prowess, and build remarkable applications that leave a lasting impact. Welcome aboard!
    </p>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<% unless user_signed_in? %>
  <%= render "welcome" %>
<% end %>
<h1>Articles</h1>
<h5>Our blog has <%= @count %> public <%= @count == 1 ? "article" : "articles" %> and counting!</h5>
<ol class="list-group">
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li class=”list-group-item list-group-item-action”>
        <%= link_to article.title, article, class: "blog-a" %>
        <% comment_comments = (article.comments.count == 1 ? "comment" : "comments") %>
        <span class="badge bg-primary rounded-pill"><%= article.comments.count %> <%= comment_comments %></span>
      </li>
    <% end %>
  <% end %>
</ol>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "New Article", new_article_path, class: "blog-new-object-label" %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="blog-post-title">
  <h1><%= @article.title %></h1>
</div>
<div class="blog-post">
  <%= simple_format(@article.body) %>
</div>
<div>
  Author
  <h6><%= @article.author %></h6>
</div>
<% if can? :edit, @article %>
  <ul>
    <li><%= link_to "Edit this article.", edit_article_path(@article) %></li>
    <li><%= link_to "Delete this article!", article_path(@article), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }, class: "link-danger" %></li>
  </ul>
<% end %>  

<h2>Comments</h2>
  <% if @article.comments.empty? %>
    <p>This article does not have any comments.</p>
  <% else %>
    <%= render @article.comments %>
  <% end %>

<% if user_signed_in? %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% else %>
  <h3>You must be signed in to leave a comment.</h3>
<% end %>  